### ISSUE TITLE
Node Js wrong Version

### ISSUE THREAD

**Issue by Bastilla123** [armindocachada/OpenVPN-Docker-GoogleAuth#10]
I have following problem that docker-compose writes me following:

=> CACHED [ 9/15] RUN sed -i "s/$host\ =\ 'localhost'/$host = 'db'/" "/var/www/html/include/config.php" &&     sed -i "s/$pass\ =\ ''/$pass = getenv('OPENVPN_ADMIN_PASSWORD')/" "/var/www/html/inc  0.0s
 => ERROR [10/15] RUN curl -L https://npmjs.org/install.sh | sh                                                                                                                                       3.2s
------                                                                                                                                                                                                     
 > [10/15] RUN curl -L https://npmjs.org/install.sh | sh:                                                                                                                                                  
0.273   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                                                                                                      
0.273                                  Dload  Upload   Total   Spent    Left  Speed                                                                                                                        
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                                                                                                             
100  3755  100  3755    0     0   9778      0 --:--:-- --:--:-- --:--:-- 87325                                                                                                                             
1.992 fetching: https://registry.npmjs.org/npm/-/npm-10.2.3.tgz
2.745 removing existing npm
2.861 ERROR: npm v10.2.3 is known not to run on Node.js v12.22.12.  This version of npm supports the following node versions: `^18.17.0 || >=20.5.0`. You can find the latest version at https://nodejs.org/.
2.861 
2.861 ERROR:
2.863 /tmp/npm.15/package/lib/utils/exit-handler.js:19
2.863   const hasLoadedNpm = npm?.config.loaded
2.863                            ^
2.863 
2.863 SyntaxError: Unexpected token '.'
2.863     at wrapSafe (internal/modules/cjs/loader.js:915:16)
2.863     at Module._compile (internal/modules/cjs/loader.js:963:27)
2.863     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2.863     at Module.load (internal/modules/cjs/loader.js:863:32)
2.863     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
2.863     at Module.require (internal/modules/cjs/loader.js:887:19)
2.863     at require (internal/modules/cjs/helpers.js:74:18)
2.863     at module.exports (/tmp/npm.15/package/lib/cli-entry.js:15:23)
2.863     at module.exports (/tmp/npm.15/package/lib/es6/validate-engines.js:39:10)
2.863     at module.exports (/tmp/npm.15/package/lib/cli.js:4:31)
2.866 failed!
------
Dockerfile_webadmin:22
--------------------
  20 |         sed -i "s/\$user\ =\ ''/\$user = getenv('OPENVPN_ADMIN_USER')/" "/var/www/html/include/config.php" && \
  21 |         sed -i "s/\$app_name\ =\ ''/\$app_name = getenv('OPENVPN_APP_NAME')/" "/var/www/html/include/config.php"
  22 | >>> RUN curl -L https://npmjs.org/install.sh | sh
  23 |     
  24 |     WORKDIR /var/www/html
--------------------
ERROR: failed to solve: process "/bin/sh -c curl -L https://npmjs.org/install.sh | sh" did not complete successfully: exit code: 1
ERROR: Service 'webadmin' failed to build : Build failed
root@sebastian-MiniAir-11:/home/sebastian/OpenVPN-Docker-GoogleAuth# node --version
v20.5.1

As you see node v20.5.1 is installed.

**Comment by aclgtrz** [comment]
change the line 22  with this

# Instalar dependencias y Node.js 18 en Debian
RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    node -v && npm -v
